---
- name: manage /etc/apt/apt.conf.d/90unattended-upgrades-updates
  block:
    - name: "set unattended-upgrades on ${distro_codename}-updates if enabled"
      when:
        - (unattended_upgrade_updates_enabled | ansible.builtin.bool)
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/90unattended-upgrades-updates
        mode: "0644"
        content: |
          Unattended-Upgrade::Origins-Pattern:: "origin=Debian,codename=${distro_codename}-updates";

    - name: "revert unattended-upgrades on ${distro_codename}-updates if not enabled"
      when:
        - not (unattended_upgrade_updates_enabled | ansible.builtin.bool)
      ansible.builtin.file:
        path: /etc/apt/apt.conf.d/90unattended-upgrades-updates
        state: absent

- name: manage /etc/apt/apt.conf.d/90unattended-upgrades-backports
  block:
    - name: set unattended-upgrades on debian-backports if enabled
      when:
        - (apt_repo_debian_backports_enabled | ansible.builtin.bool)
        - (unattended_upgrade_backports_enabled | ansible.builtin.bool)
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/90unattended-upgrades-backports
        mode: "0644"
        content: |
          Unattended-Upgrade::Origins-Pattern:: "origin=Debian Backports,codename=${distro_codename}-backports,label=Debian Backports";

    - name: revert unattended-upgrades on debian-backports if not enabled
      when:
        - not (apt_repo_debian_backports_enabled | ansible.builtin.bool)
        - not (unattended_upgrade_backports_enabled | ansible.builtin.bool)
      ansible.builtin.file:
        path: /etc/apt/apt.conf.d/90unattended-upgrades-backports
        state: absent

- name: manage /etc/apt/apt.conf.d/90unattended-upgrades-automatic-reboot
  block:
    - name: set unattended-upgrades automatic reboot if enabled
      when:
        - (unattended_upgrade_automatic_reboot_enabled | ansible.builtin.bool)
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/90unattended-upgrades-automatic-reboot
        mode: "0644"
        content: |
          // Automatically reboot *WITHOUT CONFIRMATION* if
          //  the file /var/run/reboot-required is found after the upgrade
          Unattended-Upgrade::Automatic-Reboot "true";

          // Automatically reboot even if there are users currently logged in
          // when Unattended-Upgrade::Automatic-Reboot is set to true
          //Unattended-Upgrade::Automatic-Reboot-WithUsers "true";

          // If automatic reboot is enabled and needed, reboot at the specific
          // time instead of immediately
          //  Default: "now"
          Unattended-Upgrade::Automatic-Reboot-Time "{{ unattended_upgrade_automatic_reboot_time }}";

    - name: revert unattended-upgrades automatic reboot if not enabled
      when:
        - not (unattended_upgrade_automatic_reboot_enabled | ansible.builtin.bool)
      ansible.builtin.file:
        path: /etc/apt/apt.conf.d/90unattended-upgrades-automatic-reboot
        state: absent
